### ISSUE TITLE
Documentar as pipelines

### ISSUE THREAD

**Issue by lgfa29** [mentoriaiac/cicd_centralizado#15]
### Dependencias

N/A

### Feature Request

As pipelines precisam ser documentadas para quem for usar conseguir saber quais variáveis de entrada estão disponíveis, para que elas servem, quais valores são esperados etc.

Cada pipeline deve ser documentada no arquivo `README.md` em uma seção própria, e com a seguinte estrutura e conteúdo:

    ### [nome_da_pipeline](./github/workflows/nomad_da_pipeline.yaml)
    
    <Descrição da pipeline (para que serve, quando utilizar, quais operações são feitas, ferramentas utilizadas etc.>
    
    #### Variáveis de Entrada
    
    | Nome da variável | Tipo   | Valor Padrão | Obrigatória | Descrição             |
    | ---------------- | ------ | ------------ | ----------- | --------------------- |
    | variavel_a       | string | ""           | Sim         | Variável de exemplo 1 |
    | variavel_b       | string | "valor_b"    | Não         | Variável de exemplo 2 |

    #### Segredos de Entrada
    
    | Nome do segredo | Tipo   | Valor Padrão | Obrigatório | Descrição             |
    | --------------- | ------ | ------------ | ----------- | --------------------- |
    | segredo_a       | string | ""           | Sim         | Variável de exemplo 1 |
    
    #### Exemplos de Uso

    ##### Rodar a cada push

    ```yaml
    on:
      push:
    jobs:
      docker:
        uses: "mentoriaiac/cicd_centralizado/.github/workflows/nome_da_pipeline.yaml@v1"
        with:
          variavel_b: "valor_b_sobrescrito"
    ```

    ##### <Outros exemplos relevantes>

### DoD

- [ ] Pipeline `ansible_valida_role.yaml` documentada
- [ ] Pipeline `terraform_valida_modulo.yaml` documentada
- [ ] Pipeline `versioning.yaml` documentada
