### ISSUE TITLE
Investigar erro workflow reutilizável terraform_valida_modulo

### ISSUE THREAD

**Issue by ghost** [mentoriaiac/cicd_centralizado#23]
## Descrevendo o problema

Precisamos investigar a falha na execução da actions reutilizável [terraform_valida_modulo](https://github.com/mentoriaiac/cicd_centralizado/blob/main/.github/workflows/terraform_valida_modulo.yaml). 
Na execução retorna os erros `entrada inválida do input working_directory` e `o token secreto é obrigatório`, o input `working_directory` existe no workflow centralizado mas por algum motivo retorna erro, e o `token` não está definido no arquivo de workflow centralizado mesmo assim retorna erro afirmando que esse input é requirido. 

## Reproduzindo o problema

Atualmente o cicd_centralizado encontrasse na release `v1.1.1`. Tentamos utilizar o fluxo reutilizável passando releases diferentes mesmo assim o fluxo quebra retornando sempre a mesma mensagem de erro. 
![image](https://user-images.githubusercontent.com/94695155/179397600-4955475f-7843-4417-bae8-ef676f910368.png)

Primeiro Teste:
```yaml
name: "Terraform Valida Modulo"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1"
    with:
      working_directory: "." 
```
Segundo Teste: 
```yaml
name: "Terraform Valida Modulo"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1"
```

## DoD

 - [ ] lista de atividades

**Comment by Guerlielton** [comment]
Ola @EzzioWMoreira  conseguir roda a pipeline da seguinte maneira. 
```
name: "Terraform Valida Modulo"

on: workflow_dispatch

jobs:
  terraform: 
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@v1.1.1"     
    secrets:
      token: ${{ secrets.TOKEN }}
```
Testando com o workdirectory so funcionou com a branch main.
:)
