### ISSUE TITLE
Usar tag de versão na imagem docker do tfsec do workflow Terraform Valida Módulo

### ISSUE THREAD

**Issue by edsoncelio** [mentoriaiac/cicd_centralizado#8]
### Dependencias

N/A

### Feature Request

Atualmente, no workflow `terraform_valida_modulo.yaml`, o passo responsável pela execução do `tfsec` não usa uma tag de versão na imagem docker:
```yaml
      - name: Validação do tfsec
        id: tfsec
        run: |
          docker run --rm -v $PWD:/app -w /app tfsec/tfsec .
```
Essa *issue* é para adicionar uma tag a imagem docker usada.
Pode ser a mais recente estável, checar aqui: https://hub.docker.com/r/tfsec/tfsec/tags

### DoD

- [ ] Passo de execução do tfsec usando uma imagem docker com tag de versão
